apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: task-manager-backend:latest
          imagePullPolicy: Never # Uses local minikube registry image
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: backend-secret
